# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
bioc_required: true

bioc_packages:
  - EBImage

after_script:
  - Rscript -e 'covr::codecov()'

addons:
  apt:
    packages:
      - libfftw3-dev  ## Needed by Bioc package fftwtools